# Need to change YOUR_CLUSTER_NAME and YOUR_WAVEFRONT_URL accordingly
# See https://github.com/wavefrontHQ/observability-for-kubernetes/blob/main/docs/collector/metrics.md#control-plane-metrics for more details
apiVersion: wavefront.com/v1alpha1
kind: Wavefront
metadata:
  name: wavefront
  namespace: observability-system
spec:
  clusterName: YOUR_CLUSTER_NAME
  wavefrontUrl: YOUR_WAVEFRONT_URL
  dataCollection:
    metrics:
      enable: true
  dataExport:
    wavefrontProxy:
      enable: true
---
# Need to change CONTROL_PLANE_ETCD_CA_CERTIFICATE, CONTROL_PLANE_ETCD_SERVER_CERTIFICATE, and CONTROL_PLANE_ETCD_SERVER_KEY accordingly
apiVersion: v1
kind: Secret
metadata:
  name: etcd-certs
  namespace: observability-system
type: Opaque
stringData:
  # The location of these certificates on the control plane host filesystem depends on your distribution.
  # Check your distribution documentation for how to access them. See the following as an example:
  # https://kubernetes.io/docs/setup/best-practices/certificates/#certificate-paths
  ca.crt: |
    CONTROL_PLANE_ETCD_CA_CERTIFICATE
  server.crt: |
    CONTROL_PLANE_ETCD_SERVER_CERTIFICATE
  server.key: |
    CONTROL_PLANE_ETCD_SERVER_KEY
