apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: collector
  name: coredns-control-plane-config
  namespace: {{ .Namespace }}
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: wavefront-controller-manager
    uid: {{ .ControllerManagerUID }}
  annotations:
    wavefront.com/discovery-config: 'true'
    wavefront.com/conditionally-provision: "{{ .DataCollection.Metrics.ControlPlane.Enable }}"
data:
  collector.yaml: |
    plugins:
    {{- if .Openshift }}
    - name: coredns-discovery
      type: prometheus
      selectors:
        labels:
          dns.operator.openshift.io/daemonset-dns:
          - default
      port: 9154
      path: /metrics
      scheme: https
      prefix: kubernetes.controlplane.
      convertHistograms: true
      filters:
        metricAllowList:
        - 'kubernetes.controlplane.coredns.dns.request.duration.seconds'
        - 'kubernetes.controlplane.coredns.dns.responses.total.counter'
      conf: |
        bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
        tls_config:
          ca_file: '/etc/openshift-service-ca-bundle/service-ca.crt'
          server_name: 'dns-default.openshift-dns.svc'
    {{- else }}
    - name: coredns-discovery
      type: prometheus
      selectors:
        images:
        - '*coredns:*'
        labels:
          k8s-app:
          - kube-dns
      port: 9153
      path: /metrics
      scheme: http
      prefix: kubernetes.controlplane.
      convertHistograms: true
      filters:
        metricAllowList:
        - 'kubernetes.controlplane.coredns.dns.request.duration.seconds'
        - 'kubernetes.controlplane.coredns.dns.responses.total.counter'
    {{- end }}