resources:
- service_account.yaml
- role.yaml
- cluster_role.yaml
- role_binding.yaml
- components/collector/1-collector-roles.yaml
- components/collector/2-collector-rbac.yaml
- components/autoinstrumentation/00-role-pl-cert-provisioner-role.yaml
- components/autoinstrumentation/01-role-pl-cloud-connector-ns-role.yaml
- components/autoinstrumentation/02-role-pl-updater-role.yaml
- components/autoinstrumentation/03-role-pl-vizier-crd-role.yaml
- components/autoinstrumentation/04-role-pl-vizier-metadata-role.yaml
- components/autoinstrumentation/05-role-pl-vizier-query-broker-role.yaml
- components/autoinstrumentation/06-clusterrole-pl-cloud-connector-role.yaml
- components/autoinstrumentation/07-clusterrole-pl-node-view.yaml
- components/autoinstrumentation/08-clusterrole-pl-updater-cluster-role.yaml
- components/autoinstrumentation/09-clusterrole-pl-vizier-metadata.yaml
- components/autoinstrumentation/10-rolebinding-pl-cert-provisioner-binding_pl-cert-provisioner-role_pl-cert-provisioner-service-account.yaml
- components/autoinstrumentation/11-rolebinding-pl-cloud-connector-binding_pl-cloud-connector-ns-role_cloud-conn-service-account.yaml
- components/autoinstrumentation/12-rolebinding-pl-updater-binding_pl-updater-role_pl-updater-service-account.yaml
- components/autoinstrumentation/13-rolebinding-pl-vizier-crd-binding_pl-vizier-crd-role_default.yaml
- components/autoinstrumentation/14-rolebinding-pl-vizier-crd-metadata-binding_pl-vizier-crd-role_metadata-service-account.yaml
- components/autoinstrumentation/15-rolebinding-pl-vizier-metadata-binding_pl-vizier-metadata-role_metadata-service-account.yaml
- components/autoinstrumentation/16-rolebinding-pl-vizier-query-broker-binding_pl-vizier-query-broker-role_query-broker-service-account.yaml
- components/autoinstrumentation/17-rolebinding-pl-vizier-query-broker-crd-binding_pl-vizier-crd-role_query-broker-service-account.yaml
- components/autoinstrumentation/18-clusterrolebinding-pl-cloud-connector-cluster-binding_pl-cloud-connector-role_cloud-conn-service-account.yaml
- components/autoinstrumentation/19-clusterrolebinding-pl-node-view-cluster-binding_pl-node-view_default.yaml
- components/autoinstrumentation/20-clusterrolebinding-pl-updater-cluster-binding_pl-updater-cluster-role_pl-updater-service-account.yaml
- components/autoinstrumentation/21-clusterrolebinding-pl-vizier-metadata-cluster-binding_pl-vizier-metadata_metadata-service-account.yaml
- components/autoinstrumentation/22-clusterrolebinding-pl-vizier-metadata-node-view-cluster-binding_pl-node-view_metadata-service-account.yaml
- components/logging/1-logging-roles.yaml
- components/logging/2-logging-rbac.yaml
- legacy-installation-detection/1-legacy-install-detection-roles.yaml
- legacy-installation-detection/2-legacy-install-detection-rbac.yaml