apiVersion: v1
data:
  PL_CLOUD_ADDR: "withpixie.ai:443"
  PL_CLUSTER_NAME: "kind-kind"
  PL_UPDATE_CLOUD_ADDR: "withpixie.ai:443"
kind: ConfigMap
metadata:
  annotations:
    
  creationTimestamp: null
  labels:
    
  name: pl-cloud-config
  namespace: observability-system
