apiVersion: v1
kind: Service
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: vizier-cloud-connector-svc
  namespace: observability-system
spec:
  ports:
  - name: tcp-http2
    port: 50800
    protocol: TCP
    targetPort: 50800
  selector:
    app: pl-monitoring
    component: vizier
    name: vizier-cloud-connector
    vizier-bootstrap: "true"
  type: ClusterIP