apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cert-provisioner-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-cert-provisioner-role
subjects:
- kind: ServiceAccount
  name: pl-cert-provisioner-service-account
  namespace: observability-system
