apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    
  labels:
    
    app: pl-monitoring
    component: vizier
  name: pl-vizier-query-broker-binding
  namespace: observability-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-query-broker-role
subjects:
- kind: ServiceAccount
  name: query-broker-service-account
  namespace: observability-system
